### ISSUE TITLE
Obsolete references to git.debian.org

### ISSUE THREAD

**Issue by jwilk** [paultag/tmperamental#9]
Alioth has been shut down, but there are still references to the Alioth repo in the source:

```console
$ git grep -F /git.debian.org/
debian/control:Homepage: http://git.debian.org/?p=collab-maint/tmperamental.git;a=summary
debian/control:Vcs-Git: git://git.debian.org/collab-maint/tmperamental.git
debian/control:Vcs-Browser: http://git.debian.org/?p=collab-maint/tmperamental.git
debian/copyright:Source: http://git.debian.org/?p=collab-maint/tmperamental.git;a=summary
```

Also, <http://git.debian.org/?p=collab-maint/tmperamental.git;a=summary> is set as homepage of this GitHub repo.

**Comment by dkg** [comment]
i've just done some cleanup on tmperamental at https://salsa.debian.org/debian/tmperamental which fixes these links by making them point to salsa instead.
